### ISSUE TITLE
I can’t use because it say <user> cannot be jailed

### ISSUE THREAD

**Issue by Vittorapalonne** [emilyy-dev/BetterJails#3]
I can’t use because it say <user> cannot be jailed

**Comment by emilyy-dev** [comment]
That message is shown when the player you are attempting to jail has the `betterjails.jail.exempt` permission. Make sure they aren't a server operator and also don't have the permission (depending on your permission plugin, wildcards such as `*` or `betterjails.*` will include it).

For further support please use the [discord server](https://discord.gg/GDxHt27).

**Comment by Vittorapalonne** [comment]
thank you but i can remove this from an admin? i have removed all admin from my friends that have it

**Comment by emilyy-dev** [comment]
Set the `betterjails.jail.exempt` permission to false in your permission manager. If you don't have one, you need to get one to handle that.

**Comment by Vittorapalonne** [comment]
thank you so much
